import { Stock, LeaderboardEntry, VideoItem } from "@/types/sandbox";

export const INITIAL_CASH = 100000;

export const INITIAL_STOCKS: Stock[] = [
  {
    id: "stk-1",
    symbol: "REL",
    name: "Reliance Industries",
    sector: "Energy & Conglomerate",
    currentPrice: 2840,
    previousPrice: 2750,
    change: 90,
    changePercent: 3.27,
    high: 2890,
    low: 2740,
    volume: 142500,
  },
  {
    id: "stk-2",
    symbol: "TCS",
    name: "Tata Consultancy Services",
    sector: "Technology",
    currentPrice: 3210,
    previousPrice: 3255,
    change: -45,
    changePercent: -1.38,
    high: 3280,
    low: 3190,
    volume: 89400,
  },
  {
    id: "stk-3",
    symbol: "INFY",
    name: "Infosys Ltd",
    sector: "Technology",
    currentPrice: 1920,
    previousPrice: 1880,
    change: 40,
    changePercent: 2.13,
    high: 1945,
    low: 1870,
    volume: 112000,
  },
  {
    id: "stk-4",
    symbol: "HDFC",
    name: "HDFC Bank",
    sector: "Financial Services",
    currentPrice: 1630,
    previousPrice: 1643,
    change: -13,
    changePercent: -0.79,
    high: 1655,
    low: 1620,
    volume: 204000,
  },
  {
    id: "stk-5",
    symbol: "TATAMOTORS",
    name: "Tata Motors",
    sector: "Automobile",
    currentPrice: 980,
    previousPrice: 940,
    change: 40,
    changePercent: 4.25,
    high: 995,
    low: 935,
    volume: 310000,
  },
  {
    id: "stk-6",
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    sector: "Financial Services",
    currentPrice: 1120,
    previousPrice: 1105,
    change: 15,
    changePercent: 1.36,
    high: 1132,
    low: 1100,
    volume: 165000,
  },
  {
    id: "stk-7",
    symbol: "ADANIENT",
    name: "Adani Enterprises",
    sector: "Infrastructure",
    currentPrice: 3140,
    previousPrice: 3020,
    change: 120,
    changePercent: 3.97,
    high: 3190,
    low: 3000,
    volume: 98000,
  },
  {
    id: "stk-8",
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    sector: "Telecom",
    currentPrice: 1450,
    previousPrice: 1465,
    change: -15,
    changePercent: -1.02,
    high: 1475,
    low: 1440,
    volume: 77000,
  },
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    teamId: "team-alpha",
    teamName: "Alpha Capital",
    portfolioValue: 142300,
    profitLoss: 42300,
    profitLossPercent: 42.3,
  },
  {
    rank: 2,
    teamId: "team-user",
    teamName: "Nexus Traders (You)",
    portfolioValue: 118420,
    profitLoss: 18420,
    profitLossPercent: 18.42,
    isCurrentTeam: true,
  },
  {
    rank: 3,
    teamId: "team-sigma",
    teamName: "Sigma Quant",
    portfolioValue: 114920,
    profitLoss: 14920,
    profitLossPercent: 14.92,
  },
  {
    rank: 4,
    teamId: "team-phoenix",
    teamName: "Phoenix Ventures",
    portfolioValue: 109440,
    profitLoss: 9440,
    profitLossPercent: 9.44,
  },
  {
    rank: 5,
    teamId: "team-nova",
    teamName: "Nova Arbitrage",
    portfolioValue: 102180,
    profitLoss: 2180,
    profitLossPercent: 2.18,
  },
  {
    rank: 6,
    teamId: "team-zenith",
    teamName: "Zenith Holdings",
    portfolioValue: 97500,
    profitLoss: -2500,
    profitLossPercent: -2.5,
  },
];

export const PRESET_VIDEOS: VideoItem[] = [
  {
    id: "vid-1",
    title: "Market Shock --- Global Interest Rate Surge",
    description: "Central reserve hikes interest rates unexpectedly by 75 bps causing volatility in financial and tech stocks.",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    durationSeconds: 15,
    roundRequirement: 3,
  },
  {
    id: "vid-2",
    title: "Economic Boom --- Renewable Energy Breakthrough",
    description: "Government announces massive ₹50,000 Cr green energy infrastructure subsidy package.",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    durationSeconds: 15,
    roundRequirement: 3,
  },
  {
    id: "vid-3",
    title: "Quarterly Earnings Flash --- Tech Rally",
    description: "Leading tech firms exceed revenue targets by 18%, sparking momentum across enterprise IT.",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    durationSeconds: 15,
    roundRequirement: 3,
  },
];
